### ISSUE TITLE
Crash on startup with MiniTweaks

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [Ivan-1F/Ivan-Carpet-Addition#1]
Ivan Carpet Addition version 1.2.0 crashes on startup with [MiniTweaks](https://github.com/manyrandomthings/minitweaks). It does *not* crash with version 1.1.0. No crash report was generated, but I can provide logs on both versions:

[Version 1.1.0 (no crash)](https://gist.github.com/DragonEggBedrockBreaking/23a2d4a6ad8291c9987c5f1e8120fa41)

[Version 1.2.0 (crash)](https://gist.github.com/DragonEggBedrockBreaking/af71eb4748a8461284c18e26e0e2b184)

**Comment by Ivan-1F** [comment]
This mod get conflict with minitweaks when dealing with creeper explosion because we use two ways to mixin to creeperEntity

I rewrite the creeper mixin to use the same way as minitweaks and get fixed

[ivan-carpet-addition-1.2.0+build.61.zip](https://github.com/Ivan-YFw/Ivan-Carpet-Addition/files/6008205/ivan-carpet-addition-1.2.0%2Bbuild.61.zip)
